### ISSUE TITLE
Database duplicate issue

### ISSUE THREAD

**Issue by kkkodi** [minwook-shin/notion-database#1]
If the type is the same, the database contents is duplicated.

ex)
![image](https://user-images.githubusercontent.com/86968256/124480438-36ff9900-dde2-11eb-964c-2d20463e0de9.png)

![image](https://user-images.githubusercontent.com/86968256/124480559-5a2a4880-dde2-11eb-9af2-b110d2805949.png)

**Comment by minwook-shin** [comment]
thanks you! Fixed it! 

Install notion-database==20210513.4, and check the changed code in README.
