### ISSUE TITLE
only int numbers work

### ISSUE THREAD

**Issue by akhater** [minwook-shin/notion-database#11]
Hi 

I have an issue with setting numbers only integers work, if i set 1.5 it will be taken as 1 etc...

**Comment by minwook-shin** [comment]
hello, @akhater !
fixed it now. thanks you for your response!
Install notion-database==20220628.5 and check the version.

example code : 
```
PROPERTY.set_number("float", 1.5)
```

**Comment by akhater** [comment]
Looks working fine, thank you
