### ISSUE TITLE
PROPERTY.set_number cannot be 0

### ISSUE THREAD

**Issue by akhater** [minwook-shin/notion-database#12]
Hi

I am unable to set a number to 0 - PROPERTY.set_number("number",0) returns an error

thank you

**Comment by minwook-shin** [comment]
hello, @akhater  !
fixed it now and try to writing test code to solve similar bugs.

install notion-database 20220628.6 and check the version.
( https://pypi.org/project/notion-database/20220628.6/ )

thanks again.

**Comment by akhater** [comment]
Thank you so much, let me test and get back to you

**Comment by akhater** [comment]
Confirmed working 

thanks again
