### ISSUE TITLE
Page creation fail

### ISSUE THREAD

**Issue by enrialonso** [minwook-shin/notion-database#18]
**Describe the bug**
Try to create a page (like a row into Database) and fail with this message:

```text
{
  'code': 'validation_error', 
  'message': 'Unsaved transactions: Unrecognized error.', 
  'object': 'error', 
  'status': 400
}
```

**To Reproduce**
1. Create a database
2. Try to put a page (row) into DB

**Expected behavior**
Put the page (row) on the DB

**Comment by minwook-shin** [comment]
hello, @enrialonso .
just looking at the way, it appears to be API or server error.
if you can post source code for this issue, I will try to debug it.
thanks you!

**Comment by enrialonso** [comment]
Now it works again. I think it was an error with the Notion API, and the team resolved it in a few hours! Thanks!
