### ISSUE TITLE
Adding advanced children blocks

### ISSUE THREAD

**Issue by imohitmayank** [minwook-shin/notion-database#3]
First of all, thanks for the package - it's crisp and to the point 👍 

So while playing around with the code, I tried to create a new page with some "complex" content (`Children`) that could be a combination of text, embed elements, etc. Currently, it seems the `Children` class only supports normal text, I was thinking is it possible to add support for other blocks as well? 

Btw I managed to create a workaround for my task using the following class, 
```python
class NewChildren:
    result = []

    def add_text(self, text):
        self.result.append({'object': 'block',
         'type': 'paragraph',
         'paragraph': {'text': [{'type': 'text',
         'text': {'content': text}}]}})

    def add_embed(self, link):
        self.result.append({'object': 'block',
         'type': 'embed',
         'embed': {'url': link}})
```

Maybe something on similar lines? Thanks again!

**Comment by minwook-shin** [comment]
hello.
your idea is good!
however, due to my working time, I'm slowly developing this notion package.
maybe, one of these days...?

By the way, PR is welcome.
thank you.

If start developing that feature, i'll mention again.
