### ISSUE TITLE
No results returned with `list_databases()`

### ISSUE THREAD

**Issue by RickyEsclapon** [minwook-shin/notion-database#4]
Hello! This seems like an awesome package! 

Unfortunately I can't seem to get it to work on my end. See screenshot when I follow the example with `list_databases()`:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/89109989/141599877-755b44e7-0276-4935-9785-aa9010cd3db6.png">

Any thoughts around why I'm not seeing any results returned here? I have plenty of databases in my Notion of course, and you can see if I show the result of D it seems to be a `notion_database.database.Database object` which seems correct.

I can't seem to get other endpoints like the one to retrieve a specific page to work either. Any guidance you could provide around what I'm missing here?

Thank you!
Ricky

**Comment by minwook-shin** [comment]
hello. thanks for use package!

**Comment by RickyEsclapon** [comment]
Perfect, thank you!
